services:
  api:
    image: ca-brief-21
    networks:
      - app
    ports:
      - "8045:8080"
    environment:
      HOST: 0.0.0.0
      POSTGRES_HOST: db:5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - db
 
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - db
      - app
 
volumes:
  db_data:
 
networks:
  app:
  db:
